name: Create Debian Package

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Debian package directory
        run: |

          sudo apt-get install debhelper python3-all

          mkdir -p turingmachine.pro/debian/source

          echo "1.0" >> turingmachine.pro/debian/source/format

          cp changelog turingmachine.pro/debian/
          cp compat turingmachine.pro/debian/
          cp control turingmachine.pro/debian/
          cp rules turingmachine.pro/debian/
          chmod +x turingmachine.pro/debian/rules
          cp postinst turingmachine.pro/debian
          chmod +x turingmachine.pro/debian/postinst

          mkdir -p turingmachine.pro/usr/bin/turingmachine.pro
          chmod +w turingmachine.pro/usr/bin/turingmachine.pro
          cp turingmachine.pro.py turingmachine.pro/usr/bin/turingmachine.pro
          cp ui_form.py turingmachine.pro/usr/bin/turingmachine.pro
          cp requirements.txt turingmachine.pro/usr/bin/turingmachine.pro
          cp ui_license_import.py turingmachine.pro/usr/bin/turingmachine.pro
          chmod +x turingmachine.pro/usr/bin/turingmachine.pro/turingmachine.pro.py

          mkdir -p turingmachine.pro/usr/share/applications
          echo "[Desktop Entry]" >> turingmachine.pro/usr/share/applications/turingmachine.pro.desktop
          echo "Name=TuringMachine.Pro" >> turingmachine.pro/usr/share/applications/turingmachine.pro.desktop
          echo "Exec=/usr/bin/turingmachine.pro/venv/bin/python3 /usr/bin/turingmachine.pro/turingmachine.pro.py" >> turingmachine.pro/usr/share/applications/turingmachine.pro.desktop
          echo "Icon=/usr/share/icons/turingmachine.pro.jpg" >> turingmachine.pro/usr/share/applications/turingmachine.pro.desktop
          echo "Type=Application" >> turingmachine.pro/usr/share/applications/turingmachine.pro.desktop

          mkdir -p turingmachine.pro/usr/share/icons
          cp turingmachine.pro.jpg turingmachine.pro/usr/share/icons
      
      - name: Install Build Dependencies
        run: sudo apt-get install -y devscripts

      - name: Create original tar file
        run: tar -czvf turingmachine.pro_1.0.0.orig.tar.gz turingmachine.pro


      - name: Build and Sign Debian Package
        run: |
          # Import the GPG private key
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

          export DEBFULLNAME="Pavlos Orfanidis"
          export DEBEMAIL="pavlos@orfanidis.net.gr"

          # Set GPG_TTY to point to the terminal
          export GPG_TTY=$(tty)

          export GNUPGHOME="/home/runner/.gnupg"

          # Set DEB_BUILD_OPTIONS for parallel builds
          export DEB_BUILD_OPTIONS="parallel=$(nproc)"

          # Build the source package
          debuild -S -k7F4A64C4D77ADF08A616BEF6666855A91B3897F4

          ls -la ..

          # Sign the .changes file using the GPG agent
          gpg --detach-sign --armor -u 7F4A64C4D77ADF08A616BEF6666855A91B3897F4 -o ../turingmachine.pro_1.0.0-1.dsc.asc ../turingmachine.pro_1.0.0-1.dsc
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      

      - name: List Files
        run: ls -la

#      - name: Upload DEB artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: turingmachine.pro.deb
#          path: turingmachine.pro.deb
